name: Repo Dispatch

on:
  repository_dispatch:
    types: [on-demand-test]
jobs:
  trigger_sap:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Case
        run: echo 'Chal gaya'
         issueid= ${{ github.event.client_payload.issue}}
         issue_status= ${{ github.event.client_payload.status}}
         issue_summ= ${{ github.event.client_payload.summ}}
