name: Repo Dispatch

on:
  repository_dispatch:
    types: [on-demand-test]
env:
    issue: ${{issue}}


jobs:
  trigger_sap:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Case
        run: echo 'Chal gaya'
